Repository JuliaRobotics/Caesar.jl, pull requests merged in 2018-12, with the labels that each got.

#218 multibeam factor types
  src/zmq/services/ZmqServer.jl
  src/zmq/services/config.jl
  src/zmq/services/factors/factorSerialization.jl
  src/zmq/services/session.jl
Labels: enhancement, multilang, zmq

#217 Intensity sonar map proof of concept
  examples/marine/rov/acoustics/rangeintensity.jl
Labels: example

#219 Update basic_continuousscalar.md
  docs/src/examples/basic_continuousscalar.md
Labels: documentation

#220 Update basic_slamedonut.md
  docs/src/examples/basic_slamedonut.md
Labels: documentation, upkeep

#221 Update basic_slamedonut.md
  docs/src/examples/basic_slamedonut.md
Labels: documentation

#224 add IIF inports for docs
  .travis.yml
  docs/make.jl
  docs/src/concepts/concepts.md
Labels: documentation

#225 adding vis funcs and improvements
  .travis.yml
  docs/make.jl
  docs/src/concepts/adding_variables_factors.md
  docs/src/concepts/arena_visualizations.md
  docs/src/installation_environment.md
  docs/src/vis_func_ref.md
Labels: documentation

#226 fix link in docs
  docs/make.jl
  docs/src/concepts/literature.md
  docs/src/index.md
  docs/src/installation_environment.md
Labels: documentation

#228 move references
  docs/make.jl
  docs/src/refs/literature.md
Labels: documentation

#229 Cloud/duplicatinghex
  examples/web/01_duplicate_hexagonal.jl
Labels: cloud upgrade, example, slamindb

#231 Docs/newiifdec2018
  REQUIRE
  docs/make.jl
  docs/src/func_ref.md
Labels: documentation

#232 Update installation_environment.md
  docs/src/installation_environment.md
Labels: depencies, documentation
