Repository JuliaRobotics/Caesar.jl, pull requests merged in 2018-11, with the labels that each got.

#175 Docs/refactor
  docs/make.jl
  docs/src/concepts/adding_variables_factors.md
  docs/src/concepts/arena_visualizations.md
  docs/src/concepts/building_graphs.md
  docs/src/concepts/concepts.md
  docs/src/concepts/database_interactions.md
  docs/src/concepts/zmq.md
  docs/src/examples.md
  docs/src/examples/basic_continuousscalar.md
  docs/src/examples/basic_definingfactors.md
  docs/src/examples/basic_hexagonal2d.md
  docs/src/examples/basic_slamedonut.md
  docs/src/examples/examples.md
  docs/src/examples/interm_dynpose.md
  docs/src/examples/interm_fixedlag_hexagonal.md
  docs/src/index.md
  docs/src/installation_environment.md
  examples/dfg/HexagonalDFG_PoC.jl
  src/zmq/services/factors/factorSerialization.jl
Labels: documentation, warning_potential_rabbithole

#180 fix documenter
  .travis.yml
  docs/src/concepts/building_graphs.md
Labels: Travis, documentation

#181 docs make update
  docs/make.jl
Labels: documentation

#182 Documentation fixes
  docs/make.jl
  docs/src/installation_environment.md
Labels: documentation

#178 remove previous workaround
  .travis.yml
Labels: testing, workaround

#187 add show feature for scripting
  examples/wheeled/racecar/apriltag_and_zed_slam.jl
  examples/wheeled/racecar/parsecommands.jl
  examples/wheeled/racecar/racecarUtils.jl
Labels: example, scripting

#189 Fixed-lag initial documentation
  docs/src/examples/images/fixed_lag_timing.png
  docs/src/examples/interm_fixedlag_hexagonal.md
  docs/src/index.md
Labels: documentation, example, fixed-lag

#188 Example/apriltagslam second
  examples/wheeled/racecar/apriltag_and_zed_slam.jl
  examples/wheeled/racecar/commands.sh
  examples/wheeled/racecar/racecarUtils.jl
Labels: example

#190 automate func_ref.md
  docs/make.jl
  docs/src/concepts/building_graphs.md
  docs/src/examples/basic_continuousscalar.md
  docs/src/examples/basic_definingfactors.md
  docs/src/examples/basic_hexagonal2d.md
  docs/src/examples/basic_slamedonut.md
  docs/src/examples/examples.md
  docs/src/examples/interm_dynpose.md
  docs/src/examples/interm_fixedlag_hexagonal.md
  docs/src/func_ref.md
  docs/src/reference.md
Labels: documentation

#191 add Packed_BallTreeDensity
  src/zmq/models/distributions.jl
Labels: enhancement, serialization

#193 update bash commands
  examples/wheeled/racecar/commands.sh
Labels: example, scripting

#192 Point2 replaces Point2D,
  docs/src/concepts/adding_variables_factors.md
  docs/src/concepts/building_graphs.md
  docs/src/examples/basic_hexagonal2d.md
  docs/src/examples/basic_slamedonut.md
  docs/src/examples/interm_dynpose.md
Labels: documentation, example

#194 API update identitypose6fg!,
  src/UserFunctions.jl
Labels: API change

#195 Maintenance/reducereadme
  README.md
  docs/src/index.md
Labels: documentation

#196 remove old pkg.julialang badge
  docs/src/examples/basic_continuousscalar.md
  docs/src/index.md
Labels: documentation

#199 Docs/refactor
  docs/src/examples/basic_continuousscalar.md
Labels: documentation

#204 adding IIF and RoME to docs funcs
  docs/src/func_ref.md
Labels: documentation

#206 Changes for the slamindb operation, small fix to startup message
  src/cloudgraphs/CloudGraphIntegration.jl
  src/cloudgraphs/SolverStatus.jl
  src/cloudgraphs/slamindb.jl
  src/zmq/services/ZmqServer.jl
  src/zmq/services/plotting.jl
Labels: bug, slamindb

#209 some cleanup to sasslam
  src/beamforming/MatchedFilter.jl
  test/beamforming/testFwdBackConv.jl
  test/beamforming/test_MF.jl
  test/beamforming/test_czt.jl
Labels: upkeep

#212 fixed lag docs comment
  docs/src/examples/interm_fixedlag_hexagonal.md
Labels: documentation, fixed-lag

#213 Line break on colon.
  README.md
Labels: readme

#214 fix date
  README.md
  docs/src/index.md
Labels: documentation

#215 Update basic_hexagonal2d.md
  docs/src/examples/basic_hexagonal2d.md
Labels: documentation

#216 Update zmqServer.config
  scripts/zmqServer.config
Labels: quick-fix
