Repository JuliaRobotics/Caesar.jl, pull requests merged in 2019-11, with the labels that each got.

#405 add new approxConv docs first draft
  docs/make.jl
  docs/src/examples/basic_continuousscalar.md
  docs/src/principles/approxConvDensities.md
  docs/src/principles/multiplyingDensities.md
Labels: documentation

#406 fix links
  docs/src/principles/approxConvDensities.md
Labels: documentation

#407 Update faq.md with zmq
  docs/src/faq.md
Labels: documentation

#408 add filter vs graph docs
  docs/make.jl
  docs/src/principles/approxConvDensities.md
  docs/src/principles/filterCorrespondence.md
Labels: documentation

#410 fix newline math in filterCorrespondence
  docs/src/principles/filterCorrespondence.md
Labels: documentation

#411 add image to filter correspondence
  docs/src/principles/filterCorrespondence.md
Labels: documentation

#412 Update filterCorrespondence.md
  docs/src/principles/filterCorrespondence.md
Labels: documentation

#413 Update faq.md
  docs/src/faq.md
Labels: documentation

#414 Update approxConvDensities.md
  docs/src/principles/approxConvDensities.md
Labels: documentation

#417 Update basic_slamedonut.md
  docs/src/examples/basic_slamedonut.md
Labels: canonicalexamples, documentation

#418 Update interm_fixedlag_hexagonal.md
  docs/src/examples/interm_fixedlag_hexagonal.md
Labels: documentation, example

#419 Update filterCorrespondence.md
  docs/src/principles/filterCorrespondence.md
Labels: canonicalexamples, documentation

#420 Update multiplyingDensities.md
  docs/src/principles/multiplyingDensities.md
Labels: documentation

#421 Update literature.md
  docs/src/refs/literature.md
Labels: documentation

#416 example with multimodal points environment
  examples/dev/PointsMM2D.jl
Labels: example

#409 Bayes tree docs discussion
  docs/make.jl
  docs/src/principles/bayestreePrinciples.md
Labels: documentation, inference

#424 Update bayestreePrinciples.md
  docs/src/principles/bayestreePrinciples.md
Labels: documentation

#422 Update filterCorrespondence.md
  docs/src/principles/filterCorrespondence.md
Labels: documentation

#423 Minor spell checks for docs.
  docs/src/examples/basic_hexagonal2d.md
  docs/src/examples/interm_fixedlag_hexagonal.md
Labels: documentation

#425 Update basic_hexagonal2d.md
  docs/src/examples/basic_hexagonal2d.md
Labels: documentation

#415 adding functions
  docs/src/func_ref.md
Labels: documentation

#426 continuing work on range only real time
  Project.toml
  examples/basic/SimpleBearingRange.jl
  examples/dev/SolveFactorAnalyzeMMD.jl
  examples/marine/auv/Sandshark/Funky21Problem.jl
  examples/marine/auv/Sandshark/Funky21Problem_Piecemeal.jl
  examples/marine/auv/Sandshark/FunkyContinuous.jl
  examples/marine/auv/Sandshark/Plotting.jl
  examples/marine/auv/Sandshark/SandsharkUtils.jl
  examples/marine/auv/Sandshark/Sandshark_2.jl
  examples/marine/auv/Sandshark/Sandshark_script.jl
  examples/marine/auv/Sandshark/Sandshark_script_pieces.jl
  examples/marine/auv/Sandshark/dev/OldDataUtils.jl
  examples/marine/auv/Sandshark/dev/Sandshark_2bcontinued.jl
  examples/marine/auv/Sandshark/dev/Sandshark_2cwhathappens.jl
  examples/marine/auv/Sandshark/dev/Sandshark_Graff.jl
  examples/marine/auv/Sandshark/extracttools/PlotData.py
Labels: compat, example

#427 update docs compat
  docs/Project.toml
Labels: Travis, compat, documentation

#428 remove docs Manifest file
  docs/Manifest.toml
Labels: Travis, documentation, toml

#430 Update bayestreePrinciples.md
  docs/src/principles/bayestreePrinciples.md
Labels: documentation, inference

#432 Update concepts.md
  docs/src/concepts/concepts.md
Labels: documentation

#431 Update faq.md
  docs/src/faq.md
Labels: documentation

#435 bt csm colors
  docs/src/principles/bayestreePrinciples.md
Labels: documentation

#434 fix math in concepts.md
  docs/src/concepts/concepts.md
Labels: documentation

#436 ready -> solvable
  .gitignore
  Project.toml
  examples/database/1_subGraphCopy.jl
  examples/database/ReadAcousticTest.jl
  examples/database/ReadNewData.jl
  examples/database/dbgFullLocalGraphCopy.jl
  examples/database/dev/AddDBOdoLC.jl
  examples/database/dev/BuildCloudFactorGraph.jl
  examples/database/dev/convertslamindb.jl
  examples/database/dev/testquerying.jl
  examples/database/multisession/multisessionturt213845analysis.jl
  examples/marine/rov/highend/lcmserver/lcmdbservice.jl
  examples/wheeled/vicprk_dev.jl
  src/SlamConvenienceFunctions.jl
  src/SlamInterfaceTCP.jl
  src/SlamServer.jl
  src/cloudgraphs/CloudGraphIntegration.jl
  src/cloudgraphs/ConvertGeneralSlaminDB.jl
  src/multisession/Multisession.jl
  src/zmq/models/session.jl
  src/zmq/services/ZmqServer.jl
  src/zmq/services/session.jl
  test/multilangzmq/zmqInternal.jl
Labels: API change, deprecated, upstream

#437 fix typo bayesTreePrinciples
  docs/src/principles/bayestreePrinciples.md
Labels: documentation
