Repository JuliaRobotics/Caesar.jl, pull requests merged in 2019-12, with the labels that each got.

#439 Saving data to filestore. Adding example for processor
  examples/ros/RExFeed.jl
  examples/ros/RExLidarProcessor.jl
Labels: dfg, example

#440 CSM status, just to document something
  docs/src/principles/bayestreePrinciples.md
Labels: csm, documentation, inference

#441 Update Project.toml
  Project.toml
  docs/Project.toml
Labels: compat, documentation, upstream

#442 move mmisam to principles
  docs/make.jl
Labels: documentation

#444 Update database_interactions.md
  docs/src/concepts/database_interactions.md
Labels: documentation

#443 add supersolve to faq
  docs/src/faq.md
Labels: documentation

#445 advanced Bayes tree discussion
  docs/make.jl
  docs/src/principles/initializingOnBayesTree.md
Labels: bayes tree, documentation, inference

#447 Update bayestreePrinciples.md
  docs/src/principles/bayestreePrinciples.md
Labels: bayes tree, documentation

#448 Update initializingOnBayesTree.md
  docs/src/principles/initializingOnBayesTree.md
Labels: bayes tree, documentation

#449 Update installation_environment.md
  docs/src/installation_environment.md
Labels: documentation, install

#451 Updated frontend for new radar data
  examples/ros/RExFeed.jl
Labels: example

#438 AUV example with dead reckoning tether
  examples/marine/auv/Sandshark/GenOdo.jl
  examples/marine/auv/Sandshark/LCM_SLAM_client.jl
  examples/marine/auv/Sandshark/MsgHandlers.jl
  examples/marine/auv/Sandshark/Plotting.jl
  examples/marine/auv/Sandshark/SandsharkUtils.jl
  examples/marine/auv/Sandshark/Sandshark_script_pieces.jl
  examples/marine/auv/Sandshark/dev/Funky21Problem.jl
  examples/marine/auv/Sandshark/dev/Funky21Problem_Piecemeal.jl
  examples/marine/auv/Sandshark/dev/FunkyContinuous.jl
  examples/marine/auv/Sandshark/dev/Sandshark_2.jl
  examples/marine/auv/Sandshark/dev/Sandshark_AutoinitFailCase.jl
  examples/marine/auv/Sandshark/dev/Sandshark_script.jl
Labels: dead reckon tether, example

#452 first ROS example
  examples/ros/RExFeed.jl
  examples/ros/RExLidarProcessor.jl
  examples/ros/ServiceExample.jl
  examples/ros/cpp/example.cpp
Labels: ROS, canonicalexamples, example, middleware

#458 wiki pointer for standard API definitions
  docs/src/dev/wiki.md
Labels: API, design, documentation

#454 some dev on variable order costs
  examples/dev/BruteForceTreeOrderings.jl
  examples/dev/QuestioningVariableOrder.jl
  examples/marine/auv/Sandshark/dev/Funky21Problem.jl
  examples/marine/auv/Sandshark/dev/Funky21Problem_Piecemeal.jl
  examples/marine/auv/Sandshark/dev/FunkyContinuous.jl
Labels: variable ordering

#459 Update faq.md
  docs/src/faq.md
Labels: documentation

#460 Update wiki.md
  docs/src/dev/wiki.md
Labels: documentation

#462 Update wiki.md
  docs/src/dev/wiki.md
Labels: documentation

#463 move note up
  docs/src/index.md
Labels: documentation

#465 working updates to auv example
  examples/marine/auv/Sandshark/CheckRawOdo.jl
  examples/marine/auv/Sandshark/ExampleCommand.sh
  examples/marine/auv/Sandshark/GenOdo.jl
  examples/marine/auv/Sandshark/LCM_SLAM_client.jl
  examples/marine/auv/Sandshark/MsgHandlers.jl
  examples/marine/auv/Sandshark/Plotting.jl
  examples/marine/auv/Sandshark/SandsharkUtils.jl
Labels: example

#464 Update faq.md
  docs/src/faq.md
Labels: documentation

#455 adding new radar file,
  examples/ros/RExRadarProcessor.jl
Labels: data management, example

#466 compat and getGitCommitSHA
  Project.toml
  docs/Project.toml
  docs/make.jl
  src/Caesar.jl
  src/DataUtils.jl
Labels: documentation, enhancement, maintenance

#467 fix docs
  .travis.yml
  Project.toml
  docs/Project.toml
  examples/marine/auv/Sandshark/ExampleCommand.sh
Labels: documentation

#457 add basic 1D filter style example
  examples/basic/BayesFilter1D.jl
Labels: bug, canonicalexamples

#468 1D filter link
  docs/src/principles/filterCorrespondence.md
Labels: canonicalexamples, documentation

#469 principles filter corrs first
  docs/make.jl
Labels: documentation

#470 sig proc refs
  docs/src/refs/literature.md
Labels: documentation

#393 Update .travis.yml
  .travis.yml
  Project.toml
Labels: Travis, upstream
