Repository JuliaRobotics/Caesar.jl, pull requests merged in 2019-07, with the labels that each got.

#366 add csmAnimate video blurb and link
  docs/src/concepts/mmisam_alg.md
Labels: csm, documentation

#368 Twig/dynsas/fixdeadlock into dynSAS
  examples/marine/asv/kayaks/rangeOnlySLAM.jl
  examples/marine/asv/kayaks/rangeOnlySLAM_dbg.jl
Labels: enhancement, example

#375 update tomls
  Manifest.toml
  Project.toml
Labels: toml

#376 adding more functions to docs
  docs/src/func_ref.md
Labels: documentation

#373 request reader input
  docs/src/index.md
Labels: documentation

#369 adding assignTreeHist function docs
  docs/src/func_ref.md
Labels: documentation

#372 add docs on approxConv
  docs/Project.toml
  docs/src/concepts/mmisam_alg.md
Labels: documentation, inference

#377 SAS serialization with compare
  Project.toml
  src/Caesar.jl
  src/beamforming/SASBearing2D.jl
  src/beamforming/SASUtils.jl
  test/beamforming/testExportImport.jl
Labels: factors, serialization

#379 Temp remove doc compiling
  .travis.yml
Labels: Travis, documentation, needs_testing, regression
