Repository JuliaRobotics/Caesar.jl, pull requests merged in 2019-02, with the labels that each got.

#238 Example/sandsharkcloud
  examples/dev/FreezeVariables.jl
  examples/marine/auv/Sandshark/DataUtils.jl
  examples/marine/auv/Sandshark/Plotting.jl
  examples/marine/auv/Sandshark/Sandshark_3.jl
Labels: cloud upgrade, example

#239 Bug/cleandberror
  src/cloudgraphs/CloudGraphIntegration.jl
Labels: bug, cloud upgrade, multisession

#240 add better variable factor definition
  docs/src/concepts/concepts.md
Labels: documentation

#242 Improve example headings
  REQUIRE
  docs/make.jl
Labels: documentation

#241 Feature/multisession
  REQUIRE
  docs/src/concepts/images/independentandconsensus.png
  docs/src/concepts/images/independentlandmarks.png
  docs/src/concepts/images/multisession_1initiallandmarks.png
  docs/src/concepts/images/multisession_2linkedlandmarks.png
  docs/src/concepts/images/multisessionsolve.png
  docs/src/concepts/multisession.md
  src/Caesar.jl
  src/cloudgraphs/CloudGraphIntegration.jl
  src/multisession/Multisession.jl
  tempfg.jld2
Labels: depencies, documentation, multisession

#243 Update index.md
  docs/src/index.md
Labels: documentation

#244 add sas-slam in examples
  docs/src/examples/examples.md
Labels: documentation, example

#245 Update .travis.yml
  .travis.yml
Labels: Travis, testing, versioning

#246 Update literature.md
  docs/src/refs/literature.md
Labels: documentation, literature

#248 start adding mmiSAM details
  docs/make.jl
  docs/src/concepts/mmisam_alg.md
Labels: documentation

#250 limit RoME in require file too
  REQUIRE
Labels: versioning

#254 Update mmisam_alg.md
  docs/src/concepts/mmisam_alg.md
Labels: documentation

#255 advancing requirements for amp
  REQUIRE
Labels: depencies, versioning

#257 update require and IIF api change
  .travis.yml
  examples/basic/PointTriangulation2D.jl
  examples/marine/rov/highend/lcmserver/hauvvisualizationdebug.jl
  examples/marine/rov/highend/lcmserver/server.jl
  src/cloudgraphs/CloudGraphIntegration.jl
Labels: API change, upstream, versioning

#259 Update installation_environment.md
  docs/src/installation_environment.md
Labels: documentation, visualization

#258 addNode! becomes addVariable!
  REQUIRE
  docs/src/concepts/arena_visualizations.md
  docs/src/concepts/building_graphs.md
  docs/src/examples/basic_continuousscalar.md
  docs/src/examples/basic_hexagonal2d.md
  docs/src/examples/basic_slamedonut.md
  docs/src/examples/interm_dynpose.md
  docs/src/examples/interm_fixedlag_hexagonal.md
  examples/apriltagserver/todoslam.jl
  examples/database/0_HexagonalSlam2d.jl
  examples/database/dbg_packedtype_conversions.jl
  examples/database/dev/BasicCloudGraphsSLAM.jl
  examples/database/dev/BuildCloudFactorGraph.jl
  examples/dev/FreezeVariables.jl
  examples/dfg/HexagonalDFG_PoC.jl
  examples/marine/asv/kayaks/SAS-SLAM.jl
  examples/marine/asv/kayaks/slamUtils.jl
  examples/marine/auv/Sandshark/Funky21Problem.jl
  examples/marine/auv/Sandshark/FunkyContinuous.jl
  examples/marine/auv/Sandshark/Sandshark_2.jl
  examples/marine/auv/Sandshark/Sandshark_2bcontinued.jl
  examples/marine/auv/Sandshark/Sandshark_2cwhathappens.jl
  examples/marine/auv/Sandshark/Sandshark_3.jl
  examples/marine/auv/Sandshark/devTesting.jl
  examples/marine/rov/acoustics/rangeintensity.jl
  examples/marine/rov/asfm/ASfMExample.jl
  examples/marine/rov/asfm/LRBEroll45deg.jl
  examples/marine/rov/highend/lcmserver/hauvvisualizationdebug.jl
  examples/marine/rov/highend/lcmserver/server.jl
  examples/web/01_duplicate_hexagonal.jl
  examples/wheeled/VicPrk_FrontEndUtils.jl
  examples/wheeled/racecar/dev/Img2AprilTagSLAM_local.jl
  examples/wheeled/racecar/dev/Img2AprilTagSLAM_local_randomDA.jl
  examples/wheeled/racecar/dev/quickAprilTagSLAM_local.jl
  examples/wheeled/racecar/racecarUtils.jl
  src/UserFunctions.jl
  src/cloudgraphs/ConvertGeneralSlaminDB.jl
  src/multisession/Multisession.jl
  src/zmq/services/session.jl
  test/beamforming/testFwdBackConv.jl
  test/fourdoortestcloudgraph.jl
Labels: API change, upstream, versioning

#261 adding more functions to docs
  docs/src/func_ref.md
Labels: documentation, enhancement

#260 adding local memory only feature,
  examples/marine/rov/highend/synchronySDKIntegration.jl
  src/cloudgraphs/CloudGraphIntegration.jl
Labels: enhancement, feature request

#262 Minifix for multisession to match new structure.
  src/multisession/Multisession.jl
Labels: bug, cloud upgrade, enhancement

#263 Docs/iff052api
  REQUIRE
  docs/src/func_ref.md
  src/cloudgraphs/CloudGraphIntegration.jl
Labels: documentation, enhancement

#265 update docs, fix #264
  docs/make.jl
  docs/src/func_ref.md
Labels: documentation

#266 master IIF/RoME/Plotting
  .travis.yml
Labels: Travis, documentation
