Repository JuliaRobotics/Caesar.jl, pull requests merged in 2022-07, with the labels that each got.

#872 v0.13.1-rc1
  Project.toml
  docs/make.jl
  docs/src/concepts/using_manifolds.md
  docs/src/examples/using_images.md
  docs/src/refs/literature.md
Labels: release

#874 ScatterAlignPose3 and ArrayPartition fixes
  .github/workflows/ci.yml
  Project.toml
  docs/src/examples/custom_variables.md
  src/images/Pose2AprilTag4Corners.jl
  src/images/ScatterAlignPose2.jl
  src/plotting/ScatterAlignPlotting.jl
  test/ICRA2022_tests/insufficient_data.jl
  test/ICRA2022_tests/simple_graph.jl
  test/multilangzmq/runtests.jl
  test/runtests.jl
  test/testPose2AprilTag4Corner.jl
  test/testScatterAlignPose2.jl
  test/testStashing_SAP.jl
Labels: standardization, testing, CI, factors, manifolds

#875 rosbag writer
  NEWS.md
  src/3rdParty/_PCL/entities/PCLTypes.jl
  src/3rdParty/_PCL/services/PointCloud.jl
  src/3rdParty/_PCL/services/ROSConversions.jl
  src/ros/Utils/RosbagSubscriber.jl
  src/ros/Utils/rosbagWriter.py
  test/pcl/testPointCloud2.jl
  test/testdata/_pandar_PCLPointCloud2.jldat
Labels: enhancement, feature request, ROS, pcl, point cloud

#876 _PCL.PointCloud with 3D transform apply, and testing
  NEWS.md
  Project.toml
  src/3rdParty/_PCL/services/PointCloud.jl
  test/pcl/testPointCloud2.jl
  test/runtests.jl
Labels: enhancement, testing, manifolds, pcl, point cloud

#877 restore test from depr bug
  src/zmq/services/factors/factorSerialization.jl
  test/multilangzmq/runtests.jl
  test/runtests.jl
Labels: zmq, testing, deprecated, maintenance

#878 Common transform for ScatterAlign and _PCL , Pose3
  src/3rdParty/_PCL/_PCL.jl
  src/3rdParty/_PCL/services/PointCloud.jl
  src/Caesar.jl
  src/UserFunctions.jl
  src/images/ScatterAlignPose2.jl
  src/services/_FastTransform3D.jl
Labels: standardization, factors, refactor, manifolds, pcl, point cloud

#880 update literature
  docs/src/refs/literature.md
Labels: documentation, literature, manifolds

#879 better standz. ScatterAlign as PosePose residual (Pose3)
  Project.toml
  src/images/ScatterAlignPose2.jl
  test/testScatterAlignPose2.jl
Labels: standardization, testing, factors, manifolds

#881 v0.13.2-rc1
  .github/workflows/ci.yml
  NEWS.md
  Project.toml
  docs/src/examples/custom_variables.md
  docs/src/refs/literature.md
  src/3rdParty/_PCL/_PCL.jl
  src/3rdParty/_PCL/entities/PCLTypes.jl
  src/3rdParty/_PCL/services/PointCloud.jl
  src/3rdParty/_PCL/services/ROSConversions.jl
  src/Caesar.jl
  src/UserFunctions.jl
  src/images/Pose2AprilTag4Corners.jl
  src/images/ScatterAlignPose2.jl
  src/plotting/ScatterAlignPlotting.jl
  src/ros/Utils/RosbagSubscriber.jl
  src/ros/Utils/rosbagWriter.py
  src/services/_FastTransform3D.jl
  src/zmq/services/factors/factorSerialization.jl
  test/ICRA2022_tests/insufficient_data.jl
  test/ICRA2022_tests/simple_graph.jl
  test/multilangzmq/runtests.jl
  test/pcl/testPointCloud2.jl
  test/runtests.jl
  test/testPose2AprilTag4Corner.jl
  test/testScatterAlignPose2.jl
  test/testStashing_SAP.jl
  test/testdata/_pandar_PCLPointCloud2.jldat
Labels: release

#883 Update literature.md
  docs/src/refs/literature.md
Labels: documentation, literature, maintenance, bug fix

#884 Update using_manifolds.md
  docs/src/concepts/using_manifolds.md
Labels: enhancement, documentation, manifolds

#885 consolidating simpleICP with PCL types
  Project.toml
  src/3rdParty/_PCL/_PCL.jl
  src/3rdParty/_PCL/entities/PCLTypes.jl
  src/3rdParty/_PCL/services/ICP_Simple.jl
  src/3rdParty/_PCL/services/PointCloud.jl
  src/Caesar.jl
  test/pcl/testPointCloud2.jl
  test/testdata/_PCLPointCloud2_15776.dat
  test/testdata/_pandar_PCLPointCloud2.jldat
Labels: enhancement, standardization, work in progress, pcl, point cloud

#886 update docs and some refactoring of ICP code
  NEWS.md
  Project.toml
  docs/Project.toml
  docs/make.jl
  docs/src/concepts/2d_plotting.md
  docs/src/concepts/arena_visualizations.md
  docs/src/examples/using_images.md
  docs/src/examples/using_pcl.md
  examples/dev/icp/simpleicp.jl
  src/3rdParty/_PCL/_PCL.jl
  src/3rdParty/_PCL/services/ConsolidateRigidTransform.jl
  src/3rdParty/_PCL/services/ICP_Simple.jl
  src/3rdParty/_PCL/services/PointCloud.jl
Labels: documentation, standardization, refactor, pcl, point cloud

#887 fix docs for ScatterAlign
  docs/src/examples/using_pcl.md
  src/3rdParty/_PCL/services/ICP_Simple.jl
  src/images/ScatterAlignPose2.jl
Labels: enhancement, documentation, factors

#888 v0.13.3-rc1
  .github/workflows/CompatHelper.yml
  NEWS.md
  Project.toml
  docs/Project.toml
  docs/make.jl
  docs/src/concepts/2d_plotting.md
  docs/src/concepts/arena_visualizations.md
  docs/src/concepts/solving_graphs.md
  docs/src/concepts/using_manifolds.md
  docs/src/examples/using_images.md
  docs/src/examples/using_pcl.md
  docs/src/examples/using_ros.md
  docs/src/installation_environment.md
  docs/src/refs/literature.md
  examples/dev/icp/simpleicp.jl
  src/3rdParty/_PCL/_PCL.jl
  src/3rdParty/_PCL/entities/PCLTypes.jl
  src/3rdParty/_PCL/services/ConsolidateRigidTransform.jl
  src/3rdParty/_PCL/services/ICP_Simple.jl
  src/3rdParty/_PCL/services/PointCloud.jl
  src/3rdParty/_PCL/services/ROSConversions.jl
  src/Caesar.jl
  src/images/ScatterAlignPose2.jl
  src/ros/Utils/RosbagSubscriber.jl
  test/pcl/testPointCloud2.jl
  test/testdata/_PCLPointCloud2_15776.dat
  test/testdata/_pandar_PCLPointCloud2.jldat
Labels: release

#893 add docs for initVariable!
  docs/src/concepts/solving_graphs.md
Labels: documentation, autoinit

#894 additional docs fixes
  docs/src/concepts/solving_graphs.md
  src/3rdParty/_PCL/services/ICP_Simple.jl
  src/images/ScatterAlignPose2.jl
Labels: enhancement, documentation, autoinit

#892 v0.13.3-rc2
  Project.toml
  docs/src/concepts/solving_graphs.md
  src/3rdParty/_PCL/services/ICP_Simple.jl
  src/images/ScatterAlignPose2.jl
  test/pcl/testPointCloud2.jl
Labels: release

#896 Update using_ros.md
  docs/src/examples/using_pcl.md
  docs/src/examples/using_ros.md
Labels: documentation, ROS

#897 rm bag compress kwargs
  src/ros/Utils/RosbagSubscriber.jl
  src/ros/Utils/rosbagReader.py
Labels: bug fix

#895 update docs w sampling data formats
  docs/src/examples/custom_relative_factors.md
Labels: documentation

#898 v0.13.4-rc1
  Project.toml
  docs/src/examples/custom_relative_factors.md
  docs/src/examples/using_pcl.md
  docs/src/examples/using_ros.md
  src/ros/Utils/RosbagSubscriber.jl
  src/ros/Utils/rosbagReader.py
Labels: release
