Repository JuliaRobotics/Caesar.jl, pull requests merged in 2022-04, with the labels that each got.

#831 end to end test for ICRA 2022 Tut1
  Project.toml
  test/ICRA2022_tests/simple_graph.jl
  test/runtests.jl
Labels: testing, tutorials

#833 Update mmisam_alg.md
  docs/src/concepts/mmisam_alg.md
Labels: documentation

#834 Small changes to using_manifolds.md docs
  docs/src/concepts/using_manifolds.md
Labels: documentation

#837 test ICRA Tut2,
  test/ICRA2022_tests/nongaussian_mixture.jl
  test/ICRA2022_tests/runtests.jl
  test/runtests.jl
Labels: testing, tutorials

#838 Update using_manifolds.md
  docs/src/concepts/using_manifolds.md
Labels: documentation

#842 Fix docs Manifolds.jl Q2, different logmaps
  docs/src/concepts/using_manifolds.md
Labels: documentation, bug fix, manifolds

#841 Fix manifolds Q7 projection answer
  docs/src/concepts/using_manifolds.md
Labels: enhancement, documentation, manifolds

#843 link Wikipedia on factor graphs
  docs/src/concepts/concepts.md
Labels: enhancement, documentation, standardization

#844 Update building_graphs.md
  docs/src/concepts/building_graphs.md
Labels: documentation, bug fix

#846 developing test or ICRA Tut3
  test/ICRA2022_tests/insufficient_data.jl
  test/ICRA2022_tests/nongaussian_mixture.jl
  test/ICRA2022_tests/runtests.jl
  test/ICRA2022_tests/test_data/tut3/l1_1.json
  test/ICRA2022_tests/test_data/tut3/l1_2.json
  test/ICRA2022_tests/test_data/tut3/l1_3.json
  test/ICRA2022_tests/test_data/tut3/l1_4.json
  test/ICRA2022_tests/test_data/tut3/l1_5.json
  test/ICRA2022_tests/test_data/tut3/l2_1.json
  test/ICRA2022_tests/test_data/tut3/l2_2.json
  test/ICRA2022_tests/test_data/tut3/l2_3.json
  test/ICRA2022_tests/test_data/tut3/l2_4.json
  test/ICRA2022_tests/test_data/tut3/l2_5.json
  test/ICRA2022_tests/test_data/tut3/l3_1.json
  test/ICRA2022_tests/test_data/tut3/l3_2.json
  test/ICRA2022_tests/test_data/tut3/l3_3.json
  test/ICRA2022_tests/test_data/tut3/l3_4.json
  test/ICRA2022_tests/test_data/tut3/l3_5.json
  test/ICRA2022_tests/test_data/tut3/l4_2.json
  test/ICRA2022_tests/test_data/tut3/l4_3.json
  test/ICRA2022_tests/test_data/tut3/l4_4.json
  test/ICRA2022_tests/test_data/tut3/l4_5.json
  test/ICRA2022_tests/test_data/tut3/x0_1.json
  test/ICRA2022_tests/test_data/tut3/x0_2.json
  test/ICRA2022_tests/test_data/tut3/x0_3.json
  test/ICRA2022_tests/test_data/tut3/x0_4.json
  test/ICRA2022_tests/test_data/tut3/x0_5.json
  test/ICRA2022_tests/test_data/tut3/x1_2.json
  test/ICRA2022_tests/test_data/tut3/x1_3.json
  test/ICRA2022_tests/test_data/tut3/x1_4.json
  test/ICRA2022_tests/test_data/tut3/x1_5.json
  test/ICRA2022_tests/test_data/tut3/x2_2.json
  test/ICRA2022_tests/test_data/tut3/x2_3.json
  test/ICRA2022_tests/test_data/tut3/x2_4.json
  test/ICRA2022_tests/test_data/tut3/x2_5.json
  test/ICRA2022_tests/test_data/tut3/x3_3.json
  test/ICRA2022_tests/test_data/tut3/x3_4.json
  test/ICRA2022_tests/test_data/tut3/x3_5.json
  test/ICRA2022_tests/test_data/tut3/x4_3.json
  test/ICRA2022_tests/test_data/tut3/x4_4.json
  test/ICRA2022_tests/test_data/tut3/x4_5.json
  test/ICRA2022_tests/test_data/tut3/x5_4.json
  test/ICRA2022_tests/test_data/tut3/x5_5.json
  test/ICRA2022_tests/test_data/tut3/x6_4.json
  test/ICRA2022_tests/test_data/tut3/x6_5.json
  test/ICRA2022_tests/test_data/tut3/x7_5.json
  test/ICRA2022_tests/test_data/tut3/x8_5.json
Labels: testing, tutorials

#848 depr legacy api, instead use new generateGraph_
  examples/dev/devCSMHexDelaysTest.jl
  examples/dev/devCascadeInitCSM.jl
  examples/dev/scalar/boxy.jl
  examples/dev/scalar/ex5/demtest.jl
  examples/dev/scalar/helix2D_ex5.jl
  examples/marine/auv/Sandshark/MakiePlotsFG.jl
  src/images/images.jl
  test/testPose2AprilTag4Corner.jl
Labels: upstream, deprecated, canonicalexamples, maintenance

#847 restore ScatterAlignPose2 and tests, wip
  src/images/ScatterAlignPose2.jl
  test/ICRA2022_tests/insufficient_data.jl
  test/runtests.jl
  test/testScatterAlignPose2.jl
Labels: serialization, factors, maintenance, bug fix, types, manifolds

#849 add reference for Munkres rectangular
  docs/src/refs/literature.md
Labels: documentation, standardization, assignment

#850 ScatterAlignPose2 clouds in cache
  src/images/ScatterAlignPose2.jl
  src/plotting/ScatterAlignPlotting.jl
  test/ICRA2022_tests/insufficient_data.jl
  test/testScatterAlignPose2.jl
Labels: enhancement, performance, factors, cache

#851 Standardize SAP serialization (& stashing), testing, and SDK integration
  Project.toml
  docs/make.jl
  docs/src/concepts/dataassociation.md
  docs/src/concepts/entry_data.md
  docs/src/concepts/parallel_processing.md
  docs/src/concepts/stash_and_cache.md
  src/Deprecated.jl
  src/UserFunctions.jl
  src/images/ScatterAlignPose2.jl
  src/zmq/services/ZmqServer.jl
  test/ICRA2022_tests/insufficient_data.jl
  test/runtests.jl
  test/testScatterAlignPose2.jl
  test/testStashing_SAP.jl
Labels: enhancement, performance, testing, serialization, deprecated, maintenance, types

#852 numerical test, ICRA Tut4
  test/ICRA2022_tests/insufficient_data.jl
  test/ICRA2022_tests/multihypo_corners.jl
  test/ICRA2022_tests/runtests.jl
  test/testScatterAlignPose2.jl
Labels: testing, tutorials
